-- Cria a tabela APP_USER
CREATE TABLE IF NOT EXISTS APP_USER (
    IDT_USER SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    BIRTH_DATE DATE,
    DAT_CREATED TIMESTAMP,
    DAT_UPDATED TIMESTAMP
);

-- Cria a tabela ADDRESS
CREATE TABLE IF NOT EXISTS ADDRESS (
    IDT_ADDRESS SERIAL PRIMARY KEY,
    COUNTRY VARCHAR(50) NOT NULL,
    STATE VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    COORDINATES VARCHAR(20) NOT NULL,
    IDT_USER INTEGER UNIQUE,
    CONSTRAINT fk_address_user FOREIGN KEY (IDT_USER) REFERENCES APP_USER (IDT_USER)
);

-- Cria a tabela PHONE
CREATE TABLE IF NOT EXISTS PHONE (
    IDT_PHONE SERIAL PRIMARY KEY,
    NUMBER VARCHAR(20) NOT NULL UNIQUE,
	VALIDATED BOOLEAN NOT NULL,
    COUNTRY_CODE INTEGER,
    IDT_USER INTEGER UNIQUE,
    CONSTRAINT fk_phone_user FOREIGN KEY (IDT_USER) REFERENCES APP_USER (IDT_USER)
);

-- Cria a tabela TRAINER
CREATE TABLE IF NOT EXISTS TRAINER (
    IDT_TRAINER INTEGER PRIMARY KEY,
    IGN VARCHAR(50) NOT NULL UNIQUE,
    LEVEL INTEGER NOT NULL,
    START_DATE DATE NOT NULL,
    INITIAL_XP BIGINT NOT NULL,
    INITIAL_CATCH BIGINT NOT NULL,
    PUBLIC BOOLEAN NOT NULL,
    CONSTRAINT fk_trainer_user FOREIGN KEY (IDT_TRAINER) REFERENCES APP_USER (IDT_USER)
);
